# 프록시 기본 헤더 설정
proxy_set_header Host $http_host; # 400 에러 유연화
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

# 프론트엔드로 토스할 때 거대 토큰 헤더 깨짐 방지 버퍼
proxy_buffer_size          128k;
proxy_buffers              4 256k;
proxy_busy_buffers_size    256k;

# 1️HTTP -> HTTPS 리다이렉트
server {
    listen 80;
    server_name bulletmarket.duckdns.org;
    return 301 https://$host$request_uri;
}

# 2️정식 HTTPS 라우팅
server {
    listen 443 ssl;
    server_name bulletmarket.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/drawlink.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/drawlink.duckdns.org/privkey.pem;

    # 대장 Nginx 자체의 헤더 버퍼 확장
    client_header_buffer_size 64k;
    large_client_header_buffers 4 64k;

    # 순수한 프론트엔드 컨테이너로 전달
    location / {
        proxy_pass http://bulletmarket-frontend:80;
    }

    # 백엔드 API 라우팅
    location /api/ {
        proxy_pass http://bulletmarket-backend:8080;
    }

    # 브라우저 토큰 캐시 오작동 방지용 웹소켓 블록
    location /ws/ {
        proxy_pass http://bulletmarket-backend:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_buffering off;
    }
}